goldmark:
  renderer:
    unsafe: true
  extensions:
    passthrough:
      enable: true
      delimiters:
        block:
          - - \[
            - \]
          - - $$
            - $$
        inline:
          - - \(
            - \)
highlight:
  noClasses: false

tableOfContents:
  startLevel: 2
  endLevel: 4
