colorScheme: catppuccin
defaultAppearance: dark
autoSwitchAppearance: true
enableSearch: true
enableCodeCopy: true
replyByEmail: false
mainSections:
  - posts
disableImageOptimization: false
disableImageOptimizationMD: false
disableTextInHeader: false
defaultBackgroundImage: /img/background.svg
# defaultFeaturedImage: /img/featured.svg
defaultSocialImage: /img/og.png
highlightCurrentMenuArea: true
smartTOC: true
smartTOCHideUnfocusedChildren: false
fingerprintAlgorithm: sha512
header:
  layout: fixed
footer:
  showMenu: true
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: true
  showScrollToTop: true
homepage:
  layout: background
  showRecent: false
  showRecentItems: 12
  showMoreLink: true
  showMoreLinkDest: posts
  cardView: true
  cardViewScreenWidth: false
  layoutBackgroundBlur: true
  disableHeroImageFilter: false
article:
  showDate: true
  showViews: false
  showLikes: false
  showDateOnlyInArticle: false
  showDateUpdated: true
  showAuthor: false
  showHero: true
  heroStyle: background
  layoutBackgroundBlur: true
  layoutBackgroundHeaderSpace: true
  showBreadcrumbs: true
  showDraftLabel: true
  showEdit: false
  editURL: https://github.com/nunocoracao/blowfish/tree/main/exampleSite/content
  editAppendPath: true
  seriesOpened: false
  showHeadingAnchors: true
  showPagination: true
  invertPagination: false
  showReadingTime: true
  showComments: true
  showTableOfContents: true
  showRelatedContent: true
  relatedContentLimit: 9
  showTaxonomies: true
  showAuthorsBadges: true
  showWordCount: true
  sharingLinks:
    - linkedin
    - twitter
    - bluesky
    - reddit
    - whatsapp
    - telegram
    - pinterest
    - facebook
    - email
    - line
  showZenMode: false
list:
  showHero: true
  heroStyle: background
  layoutBackgroundBlur: true
  layoutBackgroundHeaderSpace: false
  showBreadcrumbs: false
  showSummary: true
  showViews: false
  showLikes: false
  showTableOfContents: true
  showCards: false
  orderByWeight: false
  groupByYear: true
  cardView: false
  cardViewScreenWidth: false
  constrainItemsWidth: false
sitemap:
  excludedKinds: []
taxonomy:
  showTermCount: true
  showHero: true
  heroStyle: background
  showBreadcrumbs: false
  showViews: false
  showLikes: false
  showTableOfContents: true
  cardView: false
term:
  showHero: true
  heroStyle: background
  showBreadcrumbs: false
  showViews: false
  showLikes: false
  showTableOfContents: true
  groupByYear: false
  cardView: true
  cardViewScreenWidth: false
comment:
  giscus:
    repo: 2017fighting/blog
    repoId: R_kgDOO-vDjw
    category: Blog Discussion
    categoryId: DIC_kwDOO-vDj84CrxyW
    lang: zh-CN
    mapping: pathname
    reactionsEnabled: 1
    emitMetadata: 0
    inputPosition: top
    lazyLoading: true
    darkTheme: cobalt
    lightTheme: catppuccin_latte
